site_name: Bluesky Feed Digest
site_url: https://globalecologybs.github.io/bskyfeeddigest/
site_description: Curated weekly digest of Bluesky feeds

repo_url: https://github.com/khammami/bskyfeeddigest
repo_name: khammami/bskyfeeddigest
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/brands/bluesky
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight

plugins:
  - search
  - blog:
      blog_dir: blog
      post_date_format: long
      archive: true
      categories: false
      pagination: true
      pagination_per_page: 5
  - git-committers:
       repository: khammami/bskyfeeddigest
       branch: main
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/did:plc:ppsghcl5bbpgjcljnhra353s/feed/global.ecology
      name: Bluesky Feed

nav:
  - Home: index.md
  - Digests:
    - blog/index.md
  - About: about.md
